global:
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    metrics_path: /metrics
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "book-service"
    static_configs:
    - targets: ["book-service:5005"]